### ISSUE TITLE
INVALID_SIGNATURE in GetOrderHistory

### ISSUE THREAD

**Issue by NektoDron** [JKorf/Bittrex.Net#129]
09:11:08.96[15]ERROR:Server error: INVALID_SIGNATURE
TSLab.DataSource.DataSourceException: Server error: INVALID_SIGNATURE

It happens after calling GetOrderHistory. All worked fine before last night.

**Comment by JKorf** [comment]
Hi, was this a single failure or are you still getting this?

**Comment by NektoDron** [comment]
It keeps happening for my two API keys.

**Comment by JKorf** [comment]
I tested it with my key, that still works. Is it only happening with this call or also other calls?

**Comment by NektoDron** [comment]
I think It's Bittrex issue, my API keys isn't working and I can't make new one...

**Comment by Trapoh** [comment]
Hello guys,

First of all, thank you JKrof and all the contributors for this awesome work.

Unfortunately i'm getting the same error since today,
It happens only when i try to place a conditionalOrder, i get the error : 3 INVALID_SIGNATURE.

Everything else work, i can see my balance, orders updates (opening / closing orders in bittrex) but i can't place conditonal orders anymore.

I tried to generate new api keys, but still have the same issue. I just don't know what to do now, anyone experiencing the same issue ? Thank you in advance.

**Comment by JKorf** [comment]
The V2 endpoints (PlaceConditionalOrder & GetCandles) are not officially supported by Bittrex, so there was no notice of it changing, but indeed they we're failing with an INVALID_SIGNATURE error since the update. 

The fix is, as @Trapoh found out (thanks!), changing the base address to point to the international endpoint. I've changed that to be the default in the latest version as well.
