### ISSUE TITLE
BittrexSymbolOrderBook using deprecated API, please update to V3.

### ISSUE THREAD

**Issue by standimj** [JKorf/Bittrex.Net#173]
Hi, I am looking to use BittrexSymbolOrderBook and noticed it is still using the old API.  Requesting update to V3 socket API/patterns.  Thank you.

**Comment by JKorf** [comment]
Instead of adding a new class for the V3 BittrexSymbolOrderBook I've changed the original to the V3 API. I found that the sequence number is also returned in the response headers of a Post request, which made it faily easy to update to V3.

I've done some short tests and everything seemed to be working fine, but let me know if there are any issues.

**Comment by pwnzya** [comment]
Since I am not the OP here, I made a new issue #174 regarding depth parameter and sequence numbers.
