### ISSUE TITLE
Flurl

### ISSUE THREAD

**Issue by phmatray** [JKorf/Bittrex.Net#18]
Hey, folks! 
You know Flurl? That sounds crazy!
Any opinions on the thing? 
https://tmenier.github.io/Flurl/

**Comment by wklm** [comment]
I'm not sure how is it related to this repositiry

**Comment by phmatray** [comment]
I thought this project might be interesting to improve the BittrexClient class and in particular the ExecuteRequest method.

**Comment by JKorf** [comment]
I wouldn't say improve as it works fine currently. I don't know Flurl, but I've had a quick look. Seems like a fine library which could take some of the programming work of the developers hands.

I'm not going to use it for this project since it would be refactor work for hardly any improvement. Also, projects like this are a learning experience for me, and I enjoy figuring out how everything works instead of using a library that has figured it out for you.

**Comment by phmatray** [comment]
I understand your point of view.
Do you have a TODO list? I'd like to contribute to your project.
I am currently using it in a UWP project.

**Comment by JKorf** [comment]
I don't have a TODO list at the moment. If you have any suggestions please let me know.
