### ISSUE TITLE
Extra WebSocket endpoints

### ISSUE THREAD

**Issue by tritao** [JKorf/Bittrex.Net#21]
Hey, first of all thanks for this library.

I have a question. Does the library provide any way to access the extra endpoints on the WebSocket socket client, for instance `SubscribeToExchangeDeltas`?

**Comment by JKorf** [comment]
Hi, no currently only the Market Delta updates are supported. The exchange deltas has some limitations. For example, the API doesn't provide a way to unsubscribe once you're subscribed. Meaning that if we don't want updates anymore we have to close the socket, which also stops any other subscriptions running on that socket. Because it's not possible to let those play together nicely I've decided to only implement the MarketDelta updates.

**Comment by tritao** [comment]
It would be nice if we could access those APIs even with those limitations as I think it's the only feasible way to maintain order books synchronised for all markets. Would you be willing to implement support for them? I can sponsor this feature if needed, thanks.

**Comment by tritao** [comment]
Hey @JKorf, do you have any other medium where we could discuss this? Or if you're not interested, just let me know and I'll close the issue.

**Comment by cooljbg** [comment]
I found a way to unsubscribe from OrderBook  or SummaryState events without disconnection:

HubConnection hubConnection;
IHubProxy bittrexHub;
const string ApiHubUrl = "https://bittrex.com/signalr/hubs";
const string ApiHub = "CoreHub";
IDisposable hubEventUpdateSummaryState;
 IDisposable hubEventUpdateExchangeState;
bool isSubscribedForSummaryState = false;
string SelectedMarket = "";

>public void start(){
    hubConnection = new Microsoft.AspNet.SignalR.Client.HubConnection(ApiHubUrl);
   bittrexHub = hubConnection.CreateHubProxy(ApiHub);
}

>public void SubscribeForSummaryState(){
            if(isSubscribedForSummaryState ){
                     UnSubscribeFromSummaryState();
            }
            hubEventUpdateSummaryState = bittrexHub.On("updateSummaryState", data =>
            {
                Console.WriteLine("updateSummaryState: {0}", data);
            });
           isSubscribedForSummaryState = true;
}




>public void UnSubscribeFromSummaryState(){
    hubEventUpdateSummaryState.Dispose();
     isSubscribedForSummaryState = false;
}




>public void SubscribeToMarket(string _market){
    if(SelectedMarket != null || SelectedMarket.Length > 0 ){
                     UnSubscribeFromMarket(SelectedMarket);
     }
     hubEventUpdateExchangeState = bittrexHub.On("updateExchangeState", data =>
        {
                        Console.WriteLine("updateExchangeState: {0}", data);
        });
      bittrexHub.Invoke("SubscribeToExchangeDeltas", _market);
     SelectedMarket = _market;
}



>public void UnSubscribeFromMarket(string _market){
    hubEventUpdateExchangeState.Dispose();
   SelectedMarket = null;
}

**Comment by cooljbg** [comment]
Also there is "Nounce" variable in initial data from GetCurrentOrderBook() and "Nounce" variable in every OrderBookUpdate. This var is  integer  and with every next update it is incremented with 1.
Because the initial data is a lot bigger than the updates, you can use FIFO Queue for the updates and start processing the queue after the initial data is received. The queue is good to be used even after the initial data is received, because one update could be bigger than the next one.

**Comment by JKorf** [comment]
I quickly tried this but couldn't get it to work. Currently I'm kind of busy, so I can't spend too much time figuring out how to implement this nicely. If either of you have some spare time, please create a pull request of how you think it should work.

**Comment by cooljbg** [comment]
I've tried it , and it works'.The code above I wrote it here and there are possible mistakes.

**Comment by tritao** [comment]
Hey @cooljbg do you mind sending a PR for this?

**Comment by JKorf** [comment]
Order book endpoints are available in the latest release
