### ISSUE TITLE
GetCandles for EVERY currency is very slow - any way to improve?

### ISSUE THREAD

**Issue by mariocaptain** [JKorf/Bittrex.Net#34]
Hi JKorf & all,

I my Winform application, at the start I need to get candles of every currency (interval = one hour) in order to calculate the top 50 currencies that have risen the most in a given period (i.e. 1 hour, 1 day, 1 week, 1 month etc.)

However, if I run GetCandles() in a single thread, it takes up to 10 minutes to get all the candle data (because each currency has hundreds of candle entries).

I have also tried implementing multi-threading (i.e. 266 parallel threads for 266 currencies, only do once when app starts) but it doesn't improve.

Is there any way to work around this? Or what would be the best way to implement this?

Thanks in advance for any advice.

P.S. I am not sure if this "issue" is relevant but since there is no forum, I hope you don't mind that I post it here.

Kind regards,
Dave

**Comment by JKorf** [comment]
Hi Dave,

It's fine to post here. I wouldn't recommend doing 250+ calls to the API at start up. Bittrex might see it as spam and decide to temporary ban your IP address. I think they already throttle you by handling a single request at a time per IP address since you're saying that multi-threading the calls doesn't help. 

I don't have a solution at hand for what you're trying to do. You can do a GetMarketSummaries call to get the change percentage for the last 24 hours, but it's going to be hard to get the other time periods. You could keep track of the prices in a database by having a permanently running service somewhere, from which you can distill your data. Other than that I don't think you can do what you want (at least with the Bittrex API).

**Comment by mariocaptain** [comment]
Thanks for the advice. Thats what I thought too. Will try to implement the web service.
Kind regards,
Dave
