### ISSUE TITLE
Nuget Package error

### ISSUE THREAD

**Issue by mmartain** [JKorf/Bittrex.Net#38]
Unable to resolve dependencies. 'CloudFlareUtilities 0.1.0.2' is not compatible with 'Bittrex.Net 1.3.3 constraint: CloudFlareUtilities (>= 0.5.0-alpha)'.

Might be some mistake in describing the dependencies?

i think the dependencies from .NET Standard have been copied over to other .NET framework versions

**Comment by JKorf** [comment]
can you try to uninstall Bittrex.Net and then reinstall again? Someone in another issue said that fixed it for him.

**Comment by mmartain** [comment]
I already uninstalled it and deleted the package folder. Problem persist. There exists no 0.5.0 version of cloudflareutilities for .NET 4.6.1 and that is why its failing.

**Comment by LucasNatoli** [comment]
I have the same problem

**Comment by quangtho2910** [comment]
Me too. I have the same problem!

**Comment by JKorf** [comment]
I see the same problem with a clean install indeed. Can you try to manually install CloudflareUtitilities 0.5.0-alpha and after installing that try again to install Bittrex.Net. You should be able to find the 0.5.0-alpha version if you check the 'include prerelease' checkbox in the nuget package manager. That seems to work for me.

**Comment by quangtho2910** [comment]
That solve my problem but CloudflareUtilities 0.5.0-alpha installed a lot of dependencies that made my project larger. Can you help me with this? Thank you so much!

**Comment by JKorf** [comment]
I'm no expert on package management and all that stuff, but I think that that's because it's a .netstandard package. Previously I used version 0.1.2 from the top of my head which wasn't a .netstandard package, but rather just .net framework. Sadly that version was no longer working so I was forced to update it. 

I don't know if it is possible to not have all those dependencies, but I'll look into it: #41
