### ISSUE TITLE
Using the API

### ISSUE THREAD

**Issue by shovalm** [JKorf/Bittrex.Net#59]
I have a 
"Debug | Call failed to https://www.bittrex.com/api/v1.1/market/getopenorders?market=BTC-IGNIS, Error message: INVALID_SIGNATURE" error

I think it has something to do with the encryption or lack there of can someone run me through the process of using this client.

I have market public queries working fine but i cannot place or sell orders

Im using the ffg code
String apisecret= "";
            encryptor = new HMACSHA512(Encoding.UTF8.GetBytes(apisecret));
            BittrexDefaults.SetDefaultApiCredentials("api", apisecret);
            BittrexDefaults.SetDefaultLogOutput(Console.Out);
            BittrexDefaults.SetDefaultLogVerbosity(LogVerbosity.Debug);
            BittrexDefaults.SetDefaultRetries(3);

 public void buy(String ticker,decimal quant,decimal price)
        {
            
            using (var client = new BittrexClient())
            {
        
                var placedOrder = client.PlaceOrder(OrderType.Buy, ticker, quant, price);

             
            }
        }

**Comment by JKorf** [comment]
Hi,

You should not need to encrypt anything since the library should handle that for you. Using `BittrexDefaults.SetDefaultApiCredentials` should be enough. The error you get does indicate that there is something wrong with the request regarding the apiKey/apiSecret though. 

Can you validate that your api key and api secret are correct? In your paste you have `BittrexDefaults.SetDefaultApiCredentials("api", apisecret);`, I assume you do put your actual apiKey in the first parameter, not just "api"?

**Comment by shovalm** [comment]
Yes I did.i have tested the keys n all permission has been set to allow .i
have the price market summaries oullin in perfectly  it's just the private
requests that seem to not allow it

**Comment by shovalm** [comment]
I have also tried purposely making the keys wrong which gives me the
incorrect api key error

**Comment by JKorf** [comment]
Hm..
This might be the same issue as #12 . I haven't been able to reproduce that though. You could really help me solve this by disabling your current apikey/apisecret and providing them to me. You could simply make a new one. Make sure the key is really disabled if you do (you can email me if you want).

**Comment by DeanClaes** [comment]
I don't know if this is the same cause, but I recieve this error quite frequently when sending multiple requests at the same time.
