### ISSUE TITLE
TradeSell from API v2

### ISSUE THREAD

**Issue by chic99** [JKorf/Bittrex.Net#63]
Please add method to use at least /key/market/TradeSell of API version 2. 

It would be possible to set a conditional sell( to set a stop loss).

Info:
https://bittrex.com/api/v2.0/key/market/tradesell?marketname=BTC-LTC&ordertype=XXXX&quantity=1&rate=.00000012&timeInEffect=IOC&conditiontype=xxx&target=xxxx
https://bittrex.com/api/v2.0/key/market/tradebuy?marketname=BTC-LTC&ordertype=XXXX&quantity=1&rate=.00000012&timeInEffect=IOC&conditiontype=xxx&target=xxxx

OrderType:
LIMIT,
MARKET,

TimeInEffect:
GOOD_TIL_CANCELLED,
IMMEDIATE_OR_CANCEL,
FILL_OR_KILL

ConditionType:
NONE,
GREATER_THAN,
LESS_THAN,
STOP_LOSS_FIXED,
STOP_LOSS_PERCENTAGE

ConditionType and target are required, just set target to 0 for a none conditional and it is same that /market/selllimit of V1.1 API

**Comment by Cjay93** [comment]
Surely with a market sell you wouldnt need to enter a rate, like binance.

**Comment by JKorf** [comment]
Will look into this

**Comment by JKorf** [comment]
I haven't been able to get the Market orders working, not sure if it is at all possible since the website doesn't provide this functionality either. Also FillOrKill doesn't seem to work. I managed to get the conditional part working at least, so I've added that under a new function `PlaceConditionalOrder` in the latest version.
