### ISSUE TITLE
Socket support for orderbooks

### ISSUE THREAD

**Issue by mclean25** [JKorf/Bittrex.Net#75]
I've been using `Socket.SubscribeToMarketDeltaStreamAsync()` method but I've noticed that the responses you get are very slow, especially compared to this package [here](https://github.com/slazarov/python-bittrex-websocket).

Is there a reason the responses are much slower? Is there a method that we can currently use for `OrderBook`s?

**Comment by JKorf** [comment]
Hi, the marketdelta stream updates every +-10 seconds, that's just how often the websocket updates this, so I can't change that since it is configured that way on Bittrex' side. The SubscribeToExchangeDelta method provides trades and orderbook changes for a market which is pretty much real-time. Is that what you're looking for?

**Comment by mclean25** [comment]
Yes that's exactly what I was looking for. Thanks for your help!
